export default {
  SET_PAGEDATA: 'SET_PAGEDATA',
  LOAD_PAGEDATA: 'LOAD_PAGEDATA',
  SET_STATUS: 'SET_STATUS',
  PRESS_SHORTCUT: 'PRESS_SHORTCUT',
  PANEL_TOGGLE: 'PANEL_TOGGLE',
  SET_PANEL_CONTENT: 'SET_PANEL_CONTENT',
}
